### ISSUE TITLE
Selenium web-driver causes errors for tests

### ISSUE THREAD

**Issue by jilustrisimo** [learn-co-curriculum/receiving-api-posts-lab#6]
multiple students have issues with missing geckodriver.  Doing a brew install for the driver fixes it but students using the IDE or not in a Mac env may take hours getting everything set up just for the tests to work.  using the poltergeist gem works around this issue:

In the Gemfile
```
gem 'poltergeist'
```
In rails_helper.rb
```
require 'capybara/poltergeist'
Capybara.javascript_driver = :poltergeist
```

**Comment by jilustrisimo** [comment]
@aturkewi this occurs on all labs and codealongs that use the selenium-web-driver gem.

**Comment by aturkewi** [comment]
Thanks for letting us know the issue _and_ the work around @jilustrisimo 

I'm going to tag @Lukeghenco and @cernanb in on this :)
